### ISSUE TITLE
Conventional Commit Nachrichten nutzen

### ISSUE THREAD

**Issue by CzernyJ** [solawi-rhein-neckar/solawibestellsystem#12]
Ich würde gerne [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) für die Commit Messages einsetzen. Der Vorteil ist, dass wir damit später ein Changelog automatisch aus den Commit Messages generieren können z.B. mit [standard version](https://github.com/conventional-changelog/standard-version).

Dazu muss man nur das commit message template im Git Client setzen und dann das template ausfüllen.

Template
~~~~
feat,fix,docs,style,refactor,perf,test,build,ci,chore,revert(scope?): subject

body?

footer?
~~~~

**Comment by b-g-h** [comment]
Find ich gut - ich bemüh mich als Laie, es ordentlich zu führen - hatte auf der Seite nicht gesehn, dass es auch style gibt, daher war ich noch etwas unsauber :) Falls ich was falsch mach, einfach bitte Bescheid geben.
