### ISSUE TITLE
Depot-Pivot-Tabelle zum Drucken CSS-Gestaltung 

### ISSUE THREAD

**Issue by regenduft** [solawi-rhein-neckar/solawibestellsystem#13]
bei der Pivot-Tabelle für ein
einzelnes Depot um die CSS-Gestaltung kümmern, so dass ein schönes
Druckbild entsteht (in vielen Depots wird die Excel-Tabelle mit den
Bestellungen ausgelegt)?

**Comment by CzernyJ** [comment]
0 er ausblenden
2 er und 1er bei Zusatzbestellungen hervorheben
Spalten Heading hochkant formatieren

**Comment by CzernyJ** [comment]
um die Dinge aus dem obigen Kommentar zu erledigen braucht man eine css class die den Einträgen zugeordnet wird.
