### ISSUE TITLE
Depot Pivot Tabelle: Zusatzbestellung hervorheben

### ISSUE THREAD

**Issue by CzernyJ** [solawi-rhein-neckar/solawibestellsystem#15]
Wenn ein Tausch vorgenommen wurde sollte die entsprechende Zelle in der Tabelle hervorgehoben werden.

Ein Tausch ist hierbei eine einmalige Tausch eingabe kein Abo.

**Comment by b-g-h** [comment]
Hier brauche ich eine Möglichkeit, etwas auswählen zu können (class)
