### ISSUE TITLE
Tausch Popup Dialog umgestalten

### ISSUE THREAD

**Issue by CzernyJ** [solawi-rhein-neckar/solawibestellsystem#18]
Das Dropdown ist im Tausch Popup ist unübersichtlich. Wäre schön, wenn wir das etwas leichter zu bedienen gestalten.

**Comment by virtualnobi** [comment]
Es wäre schon besser, wenn die Einträge alphabetisch sortiert wären - ich habe Haferflocken fein und Haferflocken grob weit entfernt gesehen. 

Die momentane Reihenfolge ist an der Excel-Reihenfolge angelehnt (aber nicht ganz) - die kennt aber von den Mitgliedern sonst keiner. Das ist also keine Hilfe.

**Comment by virtualnobi** [comment]
Die Produktliste kann man einfach alphabetisch sortieren, aber das hilft nicht viel. 

SolawiEditor.js, Zeile 127 einfügen: 
>   126: function createInputSelect(response) {
> + 127: response.sort((a, b) => a['Name'].localeCompare(b['Name']));

Das würde die Suche unterstützen, aber es hilft noch nichts dagegen, daß "Dinkel, 3.5kg" das Korn und "Dinkelvollkorn, 2.5kg" das Mehl bezeichnet. 

Können wir die Produktbezeichnungen irgendwo (bei der Administration) ändern? 
Wen müssten wir über Namensänderungen informieren?

**Comment by regenduft** [comment]
Die Produkte stehen in der Produkt-Tabelle und deren Name kann dort
geändert werden.

Wenn die Namen der Produkte nicht identisch mit den Namen in der
Excel-Tabelle sind, muss man den Code zum Exportieren der Excel-Tabelle
so anpassen, dass er die Namen aus der Excel-Tabelle in die Namen des
Bestellsystemes übersetzt.

Am Tue, 21 Apr 2020 12:33:16 -0700
schrieb virtualnobi <notifications@github.com>:

> Die Produktliste kann man einfach alphabetisch sortieren, aber das
> hilft nicht viel. 
> 
> SolawiEditor.js, Zeile 127 einfügen: 
> >   126: function createInputSelect(response) {
> > + 127: response.sort((a, b) =>
> > a['Name'].localeCompare(b['Name']));  
> 
> Das würde die Suche unterstützen, aber es hilft noch nichts dagegen,
> daß "Dinkel, 3.5kg" das Korn und "Dinkelvollkorn, 2.5kg" das Mehl
> bezeichnet. 
> 
> Können wir die Produktbezeichnungen irgendwo (bei der Administration)
> ändern? Wen müssten wir über Namensänderungen informieren? 
>

**Comment by virtualnobi** [comment]
Im Excel sind die Namen ja deswegen klar, weil sie gruppiert sind - da gibt's eine erste Gruppenebene "Mehl" und "Korn", wo dann "Dinkel" und "Dinkelvollkorn" entsprechend einsortiert sind. 

Ich könnte ja mal bei Matthias Steinfatt, Rolf Künnemann und Katja Lauer nachfragen, ob sie Schwierigkeiten sehen, wenn die Namen eindeutiger (und länger) werden.

**Comment by regenduft** [comment]
Ich denke mal, die Excel-Liste hat absichtlich dieses Layout.

Derzeit allerdings, benutzt Michael die Excel-Liste meines Wissens noch garnicht. Wenn es mehr depots werden, wird er das aber, also sollte es weiter funktionieren.

Der Code für den Excel-Export ist derzeit in util.js

Du kannst es gerne in eine neue Datei export.js auslagern, wenn Du das gerne willst. Dann muss die neue export.js halt in allen html dateien eingebunden werden.


Die Übersetzung der Excel-Namen in Bestellsystem-Namen befindet sich in Zeile 240:

									columns[colNumber] = cell.value.replace(',5kg', '.5kg').replace('Quark', 'Quark, 400g').replace('Hafer fein', 'Haferflocken fein').replace('Hafer grob', 'Haferflocken grob').replace('Anteile', 'Gemüse').replace('Apfelsaft, 1L', 'Apfelsaft');

Es dauert ca. 2 Sekunden da noch ein replace(/^DInkel$/, 'Dinkel (Korn)') einzufügen.


Die Namen befinden sich wie gesagt in der Produkt-Tabelle.

Du rufst also das Admin-Interface auf - gehst auf "Produkt" und änderst den Namen über die Spalte "Produkt" (in der Spalte "Name" steht hingegen der Name kombiniert mit dem Gewicht, so wie im Excel - diese Spalte wird überall für die Anzeige verwendet, kann aber nicht editiert werden).


Ein Alphabetische Sortierung der Produkte halte ich für schlecht. Die Produkte sollten so (logisch) sortiert sein, wie sie auch in der Excelliste sortiert sind.


Mit Übersichtlicher gestalten meinen wir, dass Du ein schöneres Auswahlfeld einbaust.

Da gibt es schier unendlich viele DropDown-Feld-Komponenten, die es Dir ermöglichen mehrere Spalten zu verwenden (so dass z.Bsp. Tauschpunkezahl und Beschreibung noch ins Drop-Down reinkönnen) und die z.Bsp. ein Suchfeld beinhalten, und wo du z.Bsp. auch eine Gruppierung vor nehmen kannst mir Gruppenüberschriften etc.

**Comment by regenduft** [comment]
beispiel: https://www.jqueryscript.net/form/Multi-column-Dropdown-Plugin-jQuery-Inputpicker.html
