### ISSUE TITLE
Pivottabelle: Andere Spaltenreihenfolge

### ISSUE THREAD

**Issue by CzernyJ** [solawi-rhein-neckar/solawibestellsystem#25]
Die bisherige Spaltenreihenfolge ist nicht so übersichtlich. Besser wäre:

Gemüse - Kartoffeln - Fleisch - Käse - Milch - Getreide - Apfelsaft

**Comment by CzernyJ** [comment]
Bis auf die Milch haben wir die Reihenfolge angepasst

**Comment by regenduft** [comment]
db schema updated to move milch to position 06
