### ISSUE TITLE
getAjax('Solawi/Name/AbgeschlosseneWoche', ...) liefert seltsames Ergebnis

### ISSUE THREAD

**Issue by virtualnobi** [solawi-rhein-neckar/solawibestellsystem#35]
Ich wollte den Block "greeting" informativer gestalten, indem ich das "Änderungen bis Sonntag abend" durch "Keine Änderungen mehr möglich" ersetze, wenn der Sonntag vorbei ist. 

Als Annäherung dachte ich, daß in index.htm, Zeile 72, das 
`getAjax('Solawi/Name/AbgeschlosseneWoche', ...)` eine Möglichkeit bietet, frühere Wochen zu erkennen und die Anzeige entsprechend umzustellen. Aber das liefert (in dieser Woche) das Ergebnis "2019.50" - ich hätte mindestens "2020.16" erwartet.  

Frage 1 - wo kann ich die Definition von "Solawi/Name/AbgeschlosseneWoche" finden? Ich vermute mal, daß das im "backend" steckt. Kann ich das sehen? 

Frage 2 - was ist denn die intendierte Definition? Es gibt in index.htm, Zeile 277, noch ein <div> mit dem Text "Änderungen werden nicht mehr berücksichtigt" - daher kam meine Annahme, daß man damit die vergangenen Wochen bestimmen kann. 

Grüße von
nobi

**Comment by regenduft** [comment]
getAjax() liest immer nur eine Datenbanktabelle aus. In dieser Tabelle
mit dem Namen "Solawi" hat in der Zeile, die im Feld "Name" den Wert
"AbgeschlosseneWoche" stehen hat, schon lange niemand mehr was geändert.

Dieses manuelle eintragen wollten wir ja abschaffen und es stattdessen
alles automatisch machen.

Das wre auch wichtiger, als das greeting umzugestalten: Du solltest
besser alle vorkommen von AbgeschlosseneWoche durch den von dir zu
schreibenen Javascript-Code ersetzen, der die AbgeschlosseneWoche
anhand der annahme, dass die Woche immer sonntags abends abgeschlossen
wird, automatisch bestimmt.

Da sich am sonntag abend ja die Kalenderwoche sowieso ändert, muss man
da wohl nicht soviel rechnen: es genügt einfach die aktuelle
Kalenderwoche zu berechnen.

Eine Funktion dazu befindet sich in util.js



Am Tue, 21 Apr 2020 11:49:53 -0700
schrieb virtualnobi <notifications@github.com>:

> Ich wollte den Block "greeting" informativer gestalten, indem ich das
> "Änderungen bis Sonntag abend" durch "Keine Änderungen mehr möglich"
> ersetze, wenn der Sonntag vorbei ist. 
> 
> Als Annäherung dachte ich, daß in index.htm, Zeile 72, das 
> `getAjax('Solawi/Name/AbgeschlosseneWoche', ...)` eine Möglichkeit
> bietet, frühere Wochen zu erkennen und die Anzeige entsprechend
> umzustellen. Aber das liefert (in dieser Woche) das Ergebnis
> "2019.50" - ich hätte mindestens "2020.16" erwartet.  
> 
> Frage 1 - wo kann ich die Definition von
> "Solawi/Name/AbgeschlosseneWoche" finden? Ich vermute mal, daß das im
> "backend" steckt. Kann ich das sehen? 
> 
> Frage 2 - was ist denn die intendierte Definition? Es gibt in
> index.htm, Zeile 277, noch ein <div> mit dem Text "Änderungen werden
> nicht mehr berücksichtigt" - daher kam meine Annahme, daß man damit
> die vergangenen Wochen bestimmen kann. 
> 
> Grüße von
> nobi
>
